FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /workspace
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    ASPNETCORE_URLS=http://0.0.0.0:8080
CMD ["dotnet","watch","--non-interactive","run","--no-launch-profile","--urls","http://0.0.0.0:8080","--project","ImageApi.csproj"]
